name = "kas-umkm"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "kaszy-db"
database_id = "ffd48dbb-1fc4-4575-941b-bf0f8239f65f"

[vars]
CLOUDINARY_CLOUD_NAME = "dkwaosfda"
CLOUDINARY_API_KEY = "125821454392665"
CLOUDINARY_API_SECRET = "MP8kWCxdzlXl3UyxzKQJLcXQRNc"
